apiVersion: v1
kind: Service
metadata:
  name: app1-nginx-clusterip-service2
  labels:
    app: app1-ngin
spec:
  type: NodePort
  selector:
    app: app1-ngin
  ports:
    - port: 80
      targetPort: 80

